version: '3.8'

services:
  swarm-bot:
    image: sugam2060/langgraph-swarm-bot:v1.0
    container_name: langgraph-swarm-bot
    ports:
      - "8000:8000"
    environment:
      - GITHUB_WEBHOOK_SECRET=github_webhook_secret # you can create by your self just a random string
      - GITHUB_TOKEN=github_token # classic PAT is recommended
      - OPENAI_API_KEY=DUMMY_OPENAI_KEY # you can pay openai to get the key
      - LLM_PROVIDER=NVIDIA # NVIDIA or OPENAI
      - NVIDIA_API_KEY=yout-nvidia-key # go to nvidea build site and create API key (meta/llama-405b-instruct) model is used
      - LANGSMITH_TRACING=false # make it false if you dont want tracing
      - LANGSMITH_API_KEY=DUMMY_LANGSMITH_KEY # No need to provide this if langsmith_tracing=false
      - LANGSMITH_PROJECT=langsmith project name # No need to provide this if langsmith_tracing=false
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com # No need to provide this if langsmith_tracing=false
    restart: unless-stopped

networks:
  default:
    driver: bridge
