services:
  swarm-bot:
    image: sugam2060/langgraph-swarm-bot:v1.1
    container_name: langgraph-swarm-bot
    ports:
      - "8000:8000"
    environment:
      - GITHUB_WEBHOOK_SECRET=<your webhook secret> # you can generate your self just a random string
      - GITHUB_TOKEN=<your github token> # Need classic PAT token
      - LLM_PROVIDER=NVIDIA # NVIDIA or OPENAI
      - OPENAI_API_KEY=<your openai api key> # if you are using openai
      - NVIDIA_API_KEY=<your nvidia api key> # if you are using nvidia
      - DATABASE_URL=<your postgres database url> # use postgresql://postgres:postgres@postgres-db:5432/postgres
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: langgraph-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
